"""Pipeline A: MCDM Decision Analysis — End-to-End Orchestration Pipeline.

Synopsis Stage: Stage 2 — Multi-Criteria Weighting & Alternative Ranking Execution.
Theoretical Foundation: Rashmitha, Sushma & Roy (2024, Environment, Development and Sustainability).

This module orchestrates the complete 4-combination MCDM evaluation:
1. Ingests the GIS decision matrix dynamically (inferring criteria columns).
2. Computes objective criteria weights using CRITIC and Shannon Entropy.
3. Ranks candidate sites using TOPSIS and WASPAS across both weighting methods:
   - TOPSIS-CRITIC (Primary benchmark winner per Rashmitha et al.)
   - TOPSIS-Entropy
   - WASPAS-CRITIC
   - WASPAS-Entropy
4. Consolidates and exports all 4 rankings to outputs/tables/mcdm_rankings.csv.
"""

from pathlib import Path
from typing import Optional
import yaml
import numpy as np
import pandas as pd

from src.mcdm.weighting import compute_critic_weights, compute_entropy_weights
from src.mcdm.ranking import compute_topsis_ranking, compute_waspas_ranking


def run_mcdm_pipeline(
    decision_matrix_path: Path = Path("data/processed/gis/decision_matrix.csv"),
    config_path: Path = Path("config/criteria.yaml"),
    output_table_path: Path = Path("outputs/tables/mcdm_rankings.csv"),
) -> pd.DataFrame:
    """Execute the end-to-end MCDM weighting and ranking pipeline.

    Args:
        decision_matrix_path: Path to input decision matrix CSV generated by GIS pipeline.
        config_path: Path to criteria.yaml containing criteria orientation mappings.
        output_table_path: Destination path for consolidated mcdm_rankings.csv.

    Returns:
        DataFrame containing candidate site coordinates, scores, and ranks for all 4 combinations.
    """
    decision_matrix_path = Path(decision_matrix_path)
    config_path = Path(config_path)
    output_table_path = Path(output_table_path)

    print(f"[MCDM Pipeline] Loading decision matrix from: {decision_matrix_path}")
    if not decision_matrix_path.exists():
        raise FileNotFoundError(f"Decision matrix not found at '{decision_matrix_path}'. Run GIS pipeline first.")

    decision_df = pd.read_csv(decision_matrix_path)
    print(f"[MCDM Pipeline] Loaded {len(decision_df)} candidate sites.")

    # 1. Infer criteria columns dynamically (excluding spatial metadata)
    metadata_cols = ["site_id", "latitude", "longitude"]
    criteria_cols = [c for c in decision_df.columns if c not in metadata_cols]
    print(f"[MCDM Pipeline] Dynamically detected {len(criteria_cols)} criteria: {criteria_cols}")

    # 2. Resolve criteria types from config/criteria.yaml
    criteria_type_map = {}
    if config_path.exists():
        with open(config_path, "r", encoding="utf-8") as f:
            cfg = yaml.safe_load(f)
        criteria_type_map = cfg.get("criteria_types", {})

    criteria_types = [criteria_type_map.get(col, "benefit") for col in criteria_cols]
    print(f"[MCDM Pipeline] Criteria orientation mapping: {dict(zip(criteria_cols, criteria_types))}")

    # 3. Compute Objective Criteria Weights
    critic_weights = compute_critic_weights(decision_df[criteria_cols], criteria_types)
    entropy_weights = compute_entropy_weights(decision_df[criteria_cols], criteria_types)

    print("\n[MCDM Pipeline] Computed Objective Criteria Weights:")
    for col, w_c, w_e in zip(criteria_cols, critic_weights, entropy_weights):
        print(f"  - {col:<25} | CRITIC: {w_c:.4f} | Entropy: {w_e:.4f}")

    # 4. Compute All 4 Siting Ranking Combinations
    topsis_critic = compute_topsis_ranking(decision_df[criteria_cols], critic_weights, criteria_types)
    topsis_entropy = compute_topsis_ranking(decision_df[criteria_cols], entropy_weights, criteria_types)
    waspas_critic = compute_waspas_ranking(decision_df[criteria_cols], critic_weights, criteria_types)
    waspas_entropy = compute_waspas_ranking(decision_df[criteria_cols], entropy_weights, criteria_types)

    # 5. Assemble Consolidated Ranking Table
    rankings_df = pd.DataFrame()
    rankings_df["site_id"] = decision_df["site_id"]
    rankings_df["latitude"] = decision_df["latitude"]
    rankings_df["longitude"] = decision_df["longitude"]

    rankings_df["topsis_critic_score"] = topsis_critic["closeness_coefficient"].values
    rankings_df["topsis_critic_rank"] = topsis_critic["rank"].values

    rankings_df["topsis_entropy_score"] = topsis_entropy["closeness_coefficient"].values
    rankings_df["topsis_entropy_rank"] = topsis_entropy["rank"].values

    rankings_df["waspas_critic_score"] = waspas_critic["waspas_score"].values
    rankings_df["waspas_critic_rank"] = waspas_critic["rank"].values

    rankings_df["waspas_entropy_score"] = waspas_entropy["waspas_score"].values
    rankings_df["waspas_entropy_rank"] = waspas_entropy["rank"].values

    # Sort by primary benchmark (TOPSIS-CRITIC rank)
    rankings_df = rankings_df.sort_values("topsis_critic_rank").reset_index(drop=True)

    # 6. Export Output CSV
    output_table_path.parent.mkdir(parents=True, exist_ok=True)
    rankings_df.to_csv(output_table_path, index=False)
    print(f"\n[MCDM Pipeline] Consolidated rankings successfully exported to: {output_table_path}")

    # 7. Print Top-5 Candidate Sites (Primary TOPSIS-CRITIC Siting)
    print("\n[MCDM Pipeline] Top-5 Candidate Sites (TOPSIS-CRITIC):")
    top5 = rankings_df.head(5)
    for idx, row in top5.iterrows():
        print(f"  Rank {int(row['topsis_critic_rank'])}: {row['site_id']} (Lat: {row['latitude']:.4f}, Lon: {row['longitude']:.4f}) | Score: {row['topsis_critic_score']:.4f}")

    return rankings_df


if __name__ == "__main__":
    run_mcdm_pipeline()
